# This is a basic workflow to help you get started with Actions

name: Hugo CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hugo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Hugo Plugin
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: "latest"
      
      - name: Build Hugo Page
        run: |
          cd hugo
          hugo

      - name: Set Domain
        run: |
          echo shenzhen-kug.cn > hugo/public/CNAME

    
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy into GitHub Page Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: publish
          PUBLISH_DIR: ./hugo/public
          commit_message: ${{ github.event.head_commit.message }}
